const ActionTypes = {
    SHOPS: 'SHOPS',
    FAVORITESHOPS: 'FAVORITESHOPS',
    ISLOADER: 'ISLOADER',
    ISERROR: 'ISERROR',
    BOOKINGS: 'BOOKINGS',
    CURRENTSHOP: 'CURRENTSHOP',
    CURRENTUSERBOOKING: 'CURRENTUSERBOOKING',
    CURRENTBARBERBOOKING: 'CURRENTBARBERBOOKING',
    CURRENTUSER: 'CURRENTUSER',
    DATECHANGE: 'DATECHANGE',
    AVAILBLESLOTS: 'AVAILBLESLOTS',
    THANKYOUFORORDER: 'THANKYOUFORORDER',
}
export default ActionTypes;
